### ISSUE TITLE
A part of characteristic field is off screen

### ISSUE THREAD

**Issue by Jeje2201** [NaturalSolutions/NS.UI.FormBuilder#30]
Put the issue here as we can save the issue somewhere until it's fix @Naomi-Fischer 
The characteristic field is too much on the left that we loose a part of the field being off the screen.
I attach a screenshot.
![image](https://user-images.githubusercontent.com/19387127/48339251-0f26fa00-e668-11e8-9441-0f74c7472803.png)

**Comment by JWNS** [comment]
Up ?

**Comment by Jeje2201** [comment]
Guess we can close this issue as it doesn't happen anymore ?
